version : '3'

services:
  nest:
    build: ./requirements/nest/
    image: nest
    restart: always
    ports:
      - "3000:3000"
    # networks:
    #   - ts_network
    volumes:
      - nest_volume:/root/nestjs_app

volumes:
    nest_volume:
      driver_opts:
        type: volume
        o : 'bind'
        device: './nestjs_app'

# networks:
#     ts_network:
#       driver: bridge
