version : '3'

services:
  nest:
    image: nest
    build: ./requirements/nest/

    container_name: nest

    restart: always

    ports:
      - "3000:3000"
    volumes:
      - type: volume
        target: /app
        source: nest_volume
    networks:
      - ts_network

  postgres:
    image: postgres
    build: ./requirements/postgresql/

    container_name: postgres

    restart: always

    environment:
      POSTGRES_DB: nestjs_app
      POSTGRES_USER: dongyoki
      POSTGRES_PASSWORD: asdf

    ports:
      - '5432:5432'
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - ts_network

volumes:
    nest_volume:
      driver: 'local'
      driver_opts:
        type: 'none'
        o : 'bind'
        # device: './pong'
        device: './gql_test'
    db_volume:
      driver: 'local'
      driver_opts:
        type: 'none'
        o: 'bind'
        device: './db'

networks:
    ts_network:
      driver: bridge
