version : '3'

services:
  nest:
    image: nest
    build: ./requirements/nest/

    container_name: nest

    restart: always

    env_file:
      - ./requirements/.env

    ports:
      - "3000:3000"
    volumes:
      - type: volume
        target: /app
        source: nest_volume
    networks:
      - ts_network

  postgres:
    image: postgres
    build: ./requirements/postgresql/

    container_name: postgres

    restart: always

    env_file:
      - ./requirements/.env

    # environment:
      # POSTGRES_DB: nestjs_app
      # POSTGRES_USER: dongyoki
      # POSTGRES_PASSWORD: asdf

    ports:
      - '5432:5432'
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - ts_network
    
    react:
      image: react
      build: ./requirements/front/
      container_name: react
      restart: always
      volumes:
       - front_volume:/app
      networks: -ts_network
      ports:
       -3306:3306

volumes:
    nest_volume:
      driver: 'local'
      driver_opts:
        type: 'none'
        o : 'bind'
        device: './back'
    db_volume:
      driver: 'local'
      driver_opts:
        type: 'none'
        o: 'bind'
        device: './db'
    front_volume:
      driver: 'local'
      driver_opts:
        type: 'none'
        o: 'bind'
        device: './front'

networks:
    ts_network:
      driver: bridge
